### ISSUE TITLE
 Capabilities for tx power are not so explanatory

### ISSUE THREAD

**Issue by niloda** [samans/draft-ybam-rfc8561bis#14]
In mw devices that support Adaptive Coding and Modulation (ACM) the transmit power range is specific to each ACM. Typically the output power is dependent to the geometry of the transmitted constellation, therefore the output power decreases as the complexity of the modulation increases. The _minimum-power_ and _maximum-available-power_ values currently available in capabilities do not model this characteristic well enough.

The valid power ranges should be shown by the device in a sorted list indexed by modulation (_coding-modulation_). For this purpose, the acm-profile list proposed in [issue #13](https://github.com/samans/draft-ybam-rfc8561bis/issues/13) could be used, including the minimum and maximum tx power values in the acm-profile grouping.

```
grouping acm-profile {
   ...
    leaf tx-power-min {
       int8;
       units "dbm";
       ...
      "Eg: 4qam-strong"
    }
    leaf tx-power-max {
       int8;
       units "dbm";
       ...
      "Eg: 4qam-strong"
    }
}
```

With these values available, a user is able to set a valid output power value after selecting the single Coding Modulation value (_selected-cm_) or the Adaptive Coding Modulation range (_selected-min-acm_ and _selected-max-acm_).

To maintain backward compatibility, the currently modeled _minimum-power_ and _maximum-available-power_ attributes could show the minimum tx power value for _available-max-acm_ and the maximum tx power value for _available-min-acm_, respectively

**Comment by samans** [comment]
Close because covered by #13
