### ISSUE TITLE
reference coding modulation in acm mode to be selected

### ISSUE THREAD

**Issue by DanielaSpreafico** [samans/draft-ybam-rfc8561bis#16]
The selection of the Reference Mode as a value of coding-modulation value between the 'selected-min-acm' and the 'selected-max-acm'  is requested to be added as new attribute.
The attribute's name could be 'reference-cm' under the choice 'coding-modulation-mode/adaptive'  .
As in the following:

![image](https://github.com/samans/draft-ybam-rfc8561bis/assets/35307830/08f7942a-a79a-464e-9e1b-3d9284ecef88)

**Comment by DanielaSpreafico** [comment]
On ETSI EN 302 217-1 V3.2.2 (2020-02)
Section 3.1 (Definition) we can found the following:

 **reference mode** (reference equipment class and channel separation): 
in mixed-mode systems, it identifies the operative mode which characteristics (i.e. system capacity, spectral efficiency class over a given channel separation) are used (i.e. declared in the licensing process) in the link per link coordination analysis (see note)

**NOTE**: It provides the reference availability objective commonly used for the whole network (i.e. the typical 99,99 % or any other generally used by the administration concerned for the frequency coordination of licensed P-P links). When also bandwidth adaptive operation is active, the reference mode is always related to the widest channel separation used.

**Comment by samans** [comment]
In addition to the referenced-cm attribute in the coding-modulation,
need an attribute in the acm-profile:  supported-as-reference-modulation: boolean ro.
Identifies the operative mode which characteristics are used.

**Comment by samans** [comment]
1) What to call referenced-cm
2) Where to put referenced-cm
3) Discuss supported-as-reference-modulation: boolean ro.

**Comment by DanielaSpreafico** [comment]
Hi Jonas,
the reference  modulation could be configured .
I’m not sure to explain what happens in the node when it is set to a specific value (experts on that are in vacation in these days)
What I know is that it is used to set other parameters (like tx-power).

BR, Daniela

**Comment by samans** [comment]
> 1. What to call referenced-cm
> 2. Where to put referenced-cm
> 3. Discuss supported-as-reference-modulation: boolean ro.

Point 1 and 2:
referenced-cm:  below this number the transmit power can not increase.  Related to the interference calculation.  If referenced-cm is not available, the minimum value is used.
Need to clarify how this works and how it is related to ATPC.  Need to check internally and provide a suggestion.

For point 3, add this as a capability that can be retrieved.

**Comment by JonasAhl** [comment]
I'm not sure about the reference to ETSI reference mode. It talks about reference equipment class and channel separation, whereas we mean reference to a specific coding/modulation, which I believe is closer to what ETSI defines as spectrum efficiency class.

**Comment by DanielaSpreafico** [comment]
I'm trying to answer to Jonas's question.

There is an association between "spectrum efficiency class" (which roughly corresponds to modulation) and spectral mask to be respected. All in ETSI 302-217 standards:
![Etsi-image](https://github.com/samans/draft-ybam-rfc8561bis/assets/35307830/464c144b-67c3-427d-acfd-5ae9ad08c4f3)

For this reason selecting a Reference modulation as coding/modulation a spectrum efficiency class is selected.

Reference modulation is the one for which compliance with masks and other ETSI requirements is declared.
For example if I declare that my reference modulation is QPSK then it is enough for me to respect the class 2 mask and I can push the transmitted power .. then if I go up in modulation with ACM I manage by myself to guarantee functioning but I have no regulatory restrictions on emissions.
Instead if I declare reference modulation =128QAM I must ALWAYS respect the class 5b mask; even if in ACM during fading I go down to QPSK.
It could be used to ensure compatibility with adjacent channels that have already been allocated to other operators.
You can apply for a class 2 license and get it refused because that channel is adjacent to another which cannot be disturbed.
You may always have to comply with a more stringent mask because in that area and on that channel you cannot afford to disturb the neighbors (perhaps allocated to another operator) who -for example- use a higher spectral efficiency class (higher modulation).

**Comment by JonasAhl** [comment]
I agree with Daniela's description above, with one exception. 
I don't think the choice of coding (strong/light) has an impact on the compliance with the masks.
Therefore, we refer to this information as Reference Spectrum Efficiency Class and exclude the choice of coding in list of possible options and in line with the list in your description above.
Does choice of coding has a meaning in your system/case?

**Comment by DanielaSpreafico** [comment]
Jonas, what does it mean 'choice of coding (strong/light)' ? 
Do you mean that the 'strong' or 'light' modulation options are excluded to be selected as Reference Modulation?
If this is the case, yes , I agree and for that we are proposing the boolean 'supported-as-reference-modulation' in the acm-list capabilities.

**Comment by JonasAhl** [comment]
My understanding is that the type of referenced-cm is identityref based on mw-types:coding-modulation.
That list of identityrefs is a combination of selected modulation and selected coding, whereas referenced SEC or referenced-cm (according to your description) only relates to selected modulation.
I guess we could add a new list of identityrefs for reference-cm which excludes the coding and only includes what is in table 0, in your earlier comment.

**Comment by leonida-macciotta** [comment]
Dear all,

I checked and, on our equipment, the “light” and “strong” modulations happen to be in the same class as the base modulation – but this is not mandatory by itself (we’d need a modem expert here to see if this may even happen, since the code change usually improves the total throughput by a relatively small fraction of the base modulation’s throughput)

But I don’t see why a “light” or “strong” mode (modulation + coding) may not be used as a reference mode… the combination has an assigned spectral efficiency class (from the table that Daniela showed), whatever it is, that is declared by the manufacturer and will be used in the planning

We are using the combination of modulation + coding explicitly, and it should be regarded as an entity by itself, not as a “real” modulation with a differentiator applied to it, if you see my point

Cheers

Leo

**Comment by niloda** [comment]
Our devices allow the selection of the reference modulation in two different ways depending on whether ACM is enabled or not.

When the transmitted modulation is fixed, i.e. with ACM disabled, referenced-cm is assumed to be equal to selected-cm. Only ACM profiles with supported-as-fixed-modulation=true can be operated by the transmitter.

When ACM is enabled, the value of referenced-cm must be between selected-min-acm and selected-max-acm. In this case the "acm-profile:supported-as-reference-modulation: boolean:ro" attribute would declare whether the modulation (regardless of the "strong" or "light" coding value) of an ACM profile can be used as a "referenced-cm " or not.

**Comment by DanielaSpreafico** [comment]
To summarize the new attributes to add to the actual model:

1. on coding-modulation-mode:adaptive:referenced-cm identityref
2. on capability section , acm-profile: supported-as-reference-modulation: boolean ro.

**Comment by tkall** [comment]
Just a question, regarding to "supported-as-reference-modulation boolean.
It seems to me that finally only the "spectral-efficiency" characteristic has been described in the previous comments in relation to reference-cm. All other possible characteristics, eg system-capacity mentioned originally by Daniela, have not been mentioned yet and are vague.
Is the referenced-cm is actually needed for other characteristics? What happens in practice? Is there such a need?

Another point is that it is better to avoid the cm at referenced-cm that refers directly to mw-types:coding-modulation, which includes also coding light/strong.
Is it more clear to name this new leaf as reference-modulation without a reference to "coding"?

**Comment by DanielaSpreafico** [comment]
I agree to name the new configuration leaf as reference-modulation

**Comment by samans** [comment]
+--rw (coding-modulation-mode)
       |  +--:(single)
       |  |  +--rw single
       |  |     +--rw selected-cm    identityref
       |  +--:(adaptive)
       |     +--rw adaptive
       |        +--rw selected-min-acm    identityref
       |        +--rw selected-max-acm    identityref

add a +--rw reference-modulation identityref
description?

   |     +--ro nominal-tx-capacity?             uint32
       |     +--ro support-as-fixed-modulation?     boolean

add a +--ro support-as reference-modulation? boolean
description?  Reference Modulation cannot be configured but can be set by the system when support-as-reference-modulation is false.

**Comment by samans** [comment]
reference-modulation description:
reference-modulation is a reference to a coding-modulation value between the 'selected-min-acm' and the 'selected-max-acm'.

**Comment by tkall** [comment]
Hello

My opinion is that the base  mw-types:coding-modulation of the
reference-modulation leaf definition is not correct and we need instead a
new type
having the 11 values specified at the Table of the ETSI EN 302 217-1 V3.2.2
(2020-02).
This point had been mentioned before when referring to the fact that the
values of the reference-modulation are not related to the
strong / light code rates (FEC).
I think that in general, regarding to the Spectral Efficiency, that is
associated with this reference-modulation specification and that is
measured in Mbps/MHz, the term "bits per sec" refers to user data rate and
FEC is excluded.


Best regards
Thodoros Kallimanis

Στις Τρί 17 Δεκ 2024 στις 10:29 μ.μ., ο/η Scott Mansfield <
***@***.***> έγραψε:

**Comment by JonasAhl** [comment]
Hi all,
I hope it is OK that I reopen this issue.
I think Thodoros make a valid point in his comment above and we have looked into to again in a bit more detail.

Typically, as has been mentioned, it is the Tx spectrum mask that will constrain what reference mode that will be granted by a licensing body. The Tx spectrum is not modulation dependent but rather output power limited, i.e. at e.g. 128 QAM whether you fulfill the spectrum mask for SEC 2 or SEC 5L will depend on the output power set.

The term 'Reference mode'  mentioned before in this conversation, defined in ETSI EN 302 217-1 points to the spectrum efficiency rather than modulation.
In the table referenced earlier from ETSI EN 302 217-2 it is specifically stated:
"The classes reported in table 0 are for system identification only and will not imply any constraint to the actual
modulation format, provided that all the requirements of the selected class are met." 

At the time of configuration, in case a certain reference mode has been granted by the licensing body, the system needs an attribute indicating that the power setting will meet the required spectrum mask.
As the requirements for spectrum masks in ETSI 302 217-2 all refer to the Spectral Efficiency Class, a more natural configuration parameter is  Spectral Efficiency Class (SEC).
When set by an operator the system should validate that with the output power configured, so that the system will meet the spectrum mask for this SEC at any modulation.

So our proposal would be to add an attribute called SEC (Spectral Efficiency Class) with the values defined in ETSI 302 217-2 , i.e. 1, 2, 3, 4L, 4H, 5L, 5H, 6L, 6H. 7 and 8.
Also, as these requirements for fulfilling the ETSI spectrum mask do not apply for all markets, e.g.  the ANSI standard, there must also be a ‘Not Applicable’-type of value.

/JonasA

**Comment by DanielaSpreafico** [comment]
Jonas, I understood your point.
You are right that , once configured by an operator the attribute , "the system should validate that with the output power configured, so that the system will meet the spectrum mask for this SEC at any modulation".
But each Spectral Efficiency Class (SEC) reported on Table 0 of ETSI 302-217 is associated to a specific modulation state, 
so configuring a SEC or a reference-modulation provides the same information.
And this last one is more familiar for an operator also with the constraint to have reference modulation in the range of the selected modulation values on which the system has to work.

**Comment by samans** [comment]
Suggestion...

Review entire thread and consider how to model precisely what is needed by the standardard regarding what is provided to the operator by the regulator.

**Comment by demx8as6** [comment]
1. I go with any descision of the group ...
2. ... but if you ask me - I would go with  ETSI EN 302 217 - and shift the "operator" view to a GUI or operator-sspecfif view of the configuration.

**Comment by JonasAhl** [comment]
I support Martin's option 2 above.
We are defining a standard model and I think that we should adhere to other standards when available, ETSI 302-217 in this case.
I agree that operator/vendor specific interpretations or terminology could be supported in operator specific views but should not be introduced directly in the model when a standard definition is available.

I'm also repeating some of the key points from my previous comment:

- The term 'Reference mode' defined in ETSI EN 302 217-1 points to the spectrum efficiency rather than modulation. 
"The classes reported in table 0 are for system identification only and will not imply any constraint to the actual modulation format, provided that all the requirements of the selected class are met."

- The fulfillment of the required spectrum mask is not modulation dependent but rather output power limited

**Comment by italobusi** [comment]
With YANG identities it is possible to define identities for standardized values while allowing each vendor to define identities for vendor-specific values

**Comment by samans** [comment]
Change reference-modulation to spectral-efficiency-class and create a new identity that includes the spectral efficiency classes from the table above.  Naming convention...  _1, _2 etc. 
AI: Jonas to suggest descriptions (since the descriptions in the table are misleading).

**Comment by mamali68** [comment]
my humble 2 cents, spectral efficiency classes vs description. 

| Spectral Efficiency Class | Description |
| --- | --- | 
|  _1 | Interface with **modulation scheme** value 1 |
|  _2 | Interface with  **modulation scheme** value 2 |
|  _3 | Interface with **modulation scheme** value 3 |
| _4L | Interface with **modulation scheme** value 4 |
| _4H | Interface with **modulation scheme** value 5 |
| _5L | Interface with **modulation scheme** value 6 |
| _5H | Interface with **modulation scheme** value 7 |
| _6L | Interface with **modulation scheme** value 8 |
| _6H | Interface with **modulation scheme** value 9 |
|  _7 | Interface with **modulation scheme** value 10 |
|  _8 | Interface with **modulation scheme** value 11 |

**modulation scheme** defined in `grouping acm-profile` as 

```
leaf modulation-scheme {
      type uint8;
      description
        "It is the logarithm base two of the number of points in the
         transmitted constellation.  E.G.:  value would be 2 for
         4QAM, 10 fo 1024QAM, and 12 for 4096QAM.";
    }


```

**Comment by JonasAhl** [comment]
The definition of a particular SEC is not simple and I think the best is to include a reference to ETSI EN 302 217-2.

A suggestion:
See ETSI EN 302 217-2 for a complete definition of Spectrum Efficiency Class xx, including typical modulation format, required minimum Radio Interface Capacity and an associated set of spectral power density masks.

**Comment by DanielaSpreafico** [comment]
Hi all, 
I'm not convinced on the final conclusion/proposal about removing 'reference-modulation' attribute and introducing the new 'spectral-efficiency-class'.

The ETSI EN 302 217-1 and ETSI EN 302 217-2 don't state that the configuration of reference-mode is passing through the SEC configuration using the values of the second column of Table 0 (ETSI EN 302 217-2).
Any identification of a row could be allowed.
On same other cases, when the SEC is used, the 'typical modulation' is referred, without changing the meaning and the use of the reference mode/SEC

**Comment by tkall** [comment]
Hi all
Reading again ETSI EN 302 217-2 and examples there, eg 4.2.3.2. Limits, it
seems to me that the configuration of Reference Mode refers
to SEC Classes.
Eg :
"for a CS = 28 MHz three Reference Mode are declared: Class 2 (e.g. 4QAM,
32 Mbit/s min RIC), Class 4L (e.g. 16QAM, 64 Mbit/s min RIC) and Class 5HB
(e.g. 128QAM, 137 Mbit/s min RIC). "
It seems to me then that this may be followed. I.e. model Reference Mode
YANG mode but habe enum values of SEC classes.
However, I wanted to mention also the fact  that the manufacturer, not the
user, declares these reference-modes. It seems then to me that this implies
modelling
as read-only model leaves.
Furthermore, it looks likely that these declarations should be associated
to CS values (BWs) and should be a list that may include more than one
Reference Mode:

"For mixed-mode systems, the manufacturer shall declare *which Reference
Modes can be supported by the equipment, within each CS* (see example). For
each Reference Mode the equipment shall demonstrate the capability of being
compliant with the RF spectrum mask associated with the corresponding
system parameters and spectral efficiency class (see note 1). Compliance
with the RF spectrum mask can be jointly verified with the "dynamic change
of modulation" requirement in clause 4.2.6.".

Best Regards


*Theodoros Kallimanis *Principal Engineer (Systems & SW)

Department SSD
________________________________
Intracom Telecom
19.7 km New Road Peania-Markopoulo,

Peania, GR 19002
t:   +30 6671961
f:   +30 6671446
m: +30 6941636679
email ***@***.***
www.intracom-telecom.com



[image: image.png] <http://www.linkedin.com/company/intracom-telecom>[image:
image.png] <https://www.facebook.com/intracomtelecom>[image: image.png]
<https://x.com/IntracomTelecom>[image: image.png]
<http://www.youtube.com/user/IntracomTelecom>[image: image.png]
<https://www.instagram.com/intracomtelecom/>

Στις Δευ 13 Ιουλ 2026 στις 7:45 μ.μ., ο/η DanielaSpreafico <
***@***.***> έγραψε:

**Comment by DanielaSpreafico** [comment]
Hi all,
this attribute cannot be read-only because it has to be defined from management system to allow the declaration of the value. 
How to do in a differenr way?
Then I checked internally with radio experts, involved on ETSI ATTM_TM_MWT WG, and I received the following informations:
- setting only the SEC the Reference Mode is not univocally determined because different modulations could be associated to,
- it seems that the concept of Spectral Efficiency Class will be removed from the Table 0 in a next delivery of ETSI standard to leave only the  'Reference Modulation Index' and the last column (Description).

**Comment by tkall** [comment]
Hello Daniela and all

My opinion is that Reference Mode value is a combination of modulation and
air rate that corresponds to a specific SEC value.
This mode is specified by the manufacturer of the device and is fixed to
determine where to perform the licensing tests at this device.
This was my conclusion by reading the ETSI document.

Another point that I had mentioned in my previous email was that it seems
that ETSI refers to a list of Reference Modes per CS (bw value).
Anyway, all these are my rough interpretations after reading the ETSI
document.
Do you think that it may be a good idea to coordinate this issue with the
Radio people. Maybe present our thoughts to the authors of this ETSI
Standard ?

Best regards
Thodoros Kallimanis
Principal Engineer (Systems & SW)

Department SSD
________________________________
Intracom Telecom

Στις Πέμ, 16 Ιουλ 2026, 11:25 π.μ. ο χρήστης DanielaSpreafico <
***@***.***> έγραψε:
