### ISSUE TITLE
actual-received-level power is absent in topology module

### ISSUE THREAD

**Issue by jrebiffe** [samans/draft-ybam-rfc8561bis#23]
I read the [ietf-microwave-topology](https://datatracker.ietf.org/doc/html/draft-ietf-ccamp-mw-topo-yang-07#name-yang-tree) and I wonder why the `actual-received-level` power is absent : If the NMS have the SNIR it probably also known the received power. I believe that you discussed that and I am not sure if an "issue" is an appropriate section for such question.

```yang
        +--:(microwave-carrier)
           +--rw microwave-carrier!
              +--rw tx-frequency?               uint32
              +--rw rx-frequency?               uint32
              +--rw channel-separation?         uint32
              +--ro actual-tx-cm?               identityref
              +--ro actual-snir?                decimal64
              +--ro actual-transmitted-level?   decimal64
              +--ro actual-received-level?      decimal64  /* This line does not exist. */
```

In addition, I see that the module ietf-microwave-radio-link use a type `power` whereas [ietf-microwave-topology](https://datatracker.ietf.org/doc/html/rfc8561#section-2.1) directly uses type `decimal64` for power levels.

**Comment by DanielaSpreafico** [comment]
Answering to the first question (actual-received-level not present on Topology model): we identified the main attributes to use to report to NBI interface and RSL was not included.

Second question (different type for SNIR/TSL on Topology and Interface models) : at the end the  type `power`  is defined as a `decimal64`, but on the second case there is an external module (included on Interface model) where all types are listed and used for more attributes, instead in case of Topology no other attributes use it and we haven't foresee to include the same external module.

**Comment by samans** [comment]
Wait for mw-topo to publish, then work on a bis.

**Comment by samans** [comment]
Move discussion to CCAMP list for topology enhancement.
