### ISSUE TITLE
Duplication of link information in topology model

### ISSUE THREAD

**Issue by jrebiffe** [samans/draft-ybam-rfc8561bis#24]
The example of [B.1. Instance data for 2+0 mode](https://datatracker.ietf.org/doc/html/draft-ietf-ccamp-mw-topo-yang-07#name-instance-data-for-20-mode) includes JSON data from the ietf-interfaces and ietf-microwave-radio-link. If I understand properly, the module [ietf-tp-interface-reference-topology](https://datatracker.ietf.org/doc/html/draft-ietf-ccamp-if-ref-topo-yang-01) enables all information of ietf-interfaces to be reported in topology models.

Microwave information are reported twice: the example highlight this copy for `channel-separation`, `tx-frequency` and `rx-frequency`/`duplex-distance`.
**Do you also perceive this as duplication? How can we avoid that duplication?**

Side note: Interestingly, L2Interface1 and L2Interface2 have a type of ethernetCsmacd discussed in issue #19.

**Comment by samans** [comment]
Wait for mw-topo to publish, then work on a bis.

**Comment by samans** [comment]
Move discussion to CCAMP list for topology enhancement.
