### ISSUE TITLE
air-interface:alic-is-on

### ISSUE THREAD

**Issue by demx8as6** [samans/draft-ybam-rfc8561bis#27]
ALIC: Adjacent Link Interference Cancelation

The ALIC feature is not a common microwave device feature.
// @all: is this statement true?

Therefore the model should not support ALIC related configuration. 
The issue can be 'rejected'.

**Comment by alexandrustancu** [comment]
Decision on the call from 2024-01-18 was to reject this feature, since it is not supported by many vendors. The configuration can be added by vendors who support it as a proprietary augmentation.

**Comment by samans** [comment]
Closed at 2024-01-18 meeting.
