### ISSUE TITLE
BER, Errored block - EB, Mean Time between outages, Outage intesity

### ISSUE THREAD

**Issue by JonasAhl** [samans/draft-ybam-rfc8561bis#4]
based on counters implemented within the equipment 
- See document about error performance evolution from ETSI ISG mWT [[https://www.etsi.org/committee/1426-mwt](https://protect2.fireeye.com/v1/url?k=0173bcb5-5ee885b3-0173fc2e-86ee86bd5107-f62c8968fe2cf6da&q=1&e=fb4b4542-3279-4095-8a0f-50aaa9f80c55&u=https%3A%2F%2Fwww.etsi.org%2Fcommittee%2F1426-mwt)] (WI 19)
- To be discussed more in a later session

**Comment by samans** [comment]
BER and related stats are not in the scope of CCAMP.  The Outage intensity and Mean Time between outages are examples of stats that are computed and are not specific to Radio Link models.
