### ISSUE TITLE
Current Alarm Specific Problem, Historical Alarm Specific Problem

### ISSUE THREAD

**Issue by JonasAhl** [samans/draft-ybam-rfc8561bis#5]
o	Refer to the existing alarm management module?
o	What’s the “Specific Problem”?
         exists in the IETF alarm modeling [to be double checked by both sides (see bullets below)]
o	Comment: information abundance is going to be important to feed future AI algorithms
o	Specific problems.
        o	This parameter, when present, identifies further refinements to the Probable cause of the alarm. This parameter qualifies the chosen Probable cause and may be used by the managed object class definer to specify a set of identifiers for use in managed object classes.” according to ITU (X.733-1992 X.733 : Information technology - Open Systems Interconnection - Systems Management: Alarm reporting function (itu.int))
o	RFC8632 is the alarms IETF RFC https://datatracker.ietf.org/doc/html/rfc8632
o	Action: To Everyone, review RFC 8632 against the definition in X.733 and provide input of information that needs to be considered for probable cause.

**Comment by JonasAhl** [comment]
Hi all,
as Action Point for vendors, my side I checked on RFC8632 the concept of alarm ‘specific problem’ as defined on ITU X.733 .
I found it using the following leaf attribute of ‘alarm-list’ to identify an alarm instance (added to ‘resource’ and 'alarm-type-id')

leaf alarm-type-qualifier {
        type alarm-type-qualifier;

        description
          "This leaf is used when the 'alarm-type-id' leaf cannot
           uniquely identify the alarm type.  Normally, this is not the
           case, and this leaf is the empty string.”

typedef alarm-type-qualifier {
      type string;
      description
        "If an alarm type cannot be fully specified at design time by
         'alarm-type-id', this string qualifier is used in addition to
         fully define a unique alarm type.

Take into account that 'alarm-type-id' corresponds to the Probable cause of the alarm

BR, Daniela

**Comment by samans** [comment]
Follow RFC 8632, and close this issue related to the radio-link YANG work.
