### ISSUE TITLE
Maximum Link/Carrier Utilization %

### ISSUE THREAD

**Issue by JonasAhl** [samans/draft-ybam-rfc8561bis#6]
o	original intent was to support the power consumption optimization, based on actual link traffic load
        	Per carrier and per link (bundled)
o	Interval?
        	Action:  everyone to consider and bring proposals/thoughts on measurement interval granularity
        	current 15 minute integration time is too long for advanced applications
                •	For non-continuous transmission (packet transmission) the integration time should not be too short
                        o	Integration time could be much shorter than 15 minutes, reporting max and min could be on a 15 minutes interval
o	Percentage relative to what?
        	maximum and minimum modulation (static)
        	Action: everyone to consider and bring contributions that provide clarity on the interaction between electrical power consumption and traffic

**Comment by samans** [comment]
Review the discussion here: https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-mw-topo-yang/issues/3
Is this a measurement that is done on the link layer or ethernet layer?
What is the time-period used to calculate this utilization?  Can’t be instantaneous but has to be over a period of time (so how long?).

**Comment by samans** [comment]
From the radio side there is no utilization, utilization is calculated by throughput and bandwidth utilization percentage at the application level.
