### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by JonasAhl** [samans/draft-ybam-rfc8561bis#7]
o	Latency of what?  Link? Service? Defined on Ethernet traffic, any requirements on interval for measurement of latency?
o	Requirements related to supporting configuration of L2 or L3 service based on latency, availability, and capacity.
o	Differentiate between what needs to be stored/retrieved/measured from the equipment, or supported by an end-to-end protocol like TWAMP.
o	Ethernet OAM IEEE CFM (current CFM YANG found here: yang/standard/ieee/published/802.1 at master · YangModels/yang · GitHub), ITU-T work on G.8052.1 (G.8052.1 : Operation, administration, maintenance (OAM) management information and data models for the Ethernet-transport network element (itu.int))
o	Applicability of current tools to the given requirements based on new features like slicing.
o	Action: to the equipment vendors to propose what support is available on the equipment (capabilities may be beyond the microwave modeling work, more related to system-level OAM measurement/management).
o	Action: identify the YANG models that identify the latency measurement

**Comment by samans** [comment]
Parameter inside each modulation mode, that provides information about the latency of the processing in the microwave device.  Could be used as input into calculating if a service is possible based on the equipment in the path.

**Comment by samans** [comment]
Latency doesn't belong in the Radio Link model.  Something that is calculated at the application layer.
