### ISSUE TITLE
Electrical Power Consumption

### ISSUE THREAD

**Issue by JonasAhl** [samans/draft-ybam-rfc8561bis#8]
o	Calculated how?  Consumption per link?  Per carrier? Or Aggregate for the node?
o	Suggestion: A system is modular, the modules are chassis that take power, so power consumption is measured at the granularity of the chassis.  Take this to the carriers to determine if this provides the power consumption information needed.
o	Action: proposal for electrical power consumption model (and granularity of measurement)
o	Action: Can carriers agree that chassis-level measurement is sufficient.

**Comment by samans** [comment]
Have one number per chassis.  Information about power consumption is not microwave specific so, not needed here in the radio link model.
